# Generated by Django 3.1.6 on 2021-02-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=200)),
                ('Department_ID', models.CharField(max_length=100)),
                ('Module_Name', models.CharField(max_length=200)),
                ('Module_ID', models.CharField(max_length=100)),
                ('Faculty', models.CharField(max_length=200)),
                ('Module_Lead', models.CharField(max_length=100)),
                ('Catalogue_Link', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
    ]
