# Generated by Django 3.1.6 on 2021-02-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='Credit_Value',
            field=models.IntegerField(default=0),
        ),
    ]
