# Generated by Django 3.1.6 on 2021-02-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_publication_credit_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='Module',
        ),
    ]
