# Generated by Django 3.1.6 on 2021-02-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210212_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
