# Generated by Django 3.1.6 on 2021-02-15 20:05

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210215_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='data',
            field=App.models.JSONField(blank=True, null=True),
        ),
    ]
