# Generated by Django 3.1.6 on 2021-03-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210215_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
