# Generated by Django 3.1.6 on 2021-03-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20210302_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='assignedSDG',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
