# Generated by Django 3.1.6 on 2021-03-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_publication_assignedsdg'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assignedSDG',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
